//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Services
{
    using System;
    using System.Collections.Generic;
    
    using CRM.Model;
    using CRM.IServices;
    using CRM.IRepository;
    using CRM.Common;
        /// <summary>
        /// 负责每个数据表的数据操作
        /// </summary>
    public partial class sysPermissListServices:BaseServices<sysPermissList>,IsysPermissListServices
    {
    ///定义构造函数，接收autofac将数据仓储层的具体实现类的对象注入到此类中
    IsysPermissListRepository dal;
    public sysPermissListServices(IsysPermissListRepository dal) 
    	{
    		this.dal=dal;
    		base.baseDal=dal;
    	}
        #region 特殊处理
        /// <summary>
        /// 权限按钮缓存
        /// </summary>
        /// <param name="userid"></param>
        /// <returns></returns>
    public List<Usp_GetFunctionsForUser_Result> GetFunctionsForUserByCache(int userid)
    {
        string cacheKey = Keys.PermissFunctionsForUser+userid;
        //从缓存获取用户的权限
        object data = CacheMgr.GetData<List<Usp_GetFunctionsForUser_Result>>(cacheKey);
        if (data == null)
        {
            //从数据库获取权限按钮数据
            var prmisslist = baseDal.RunProc<Usp_GetFunctionsForUser_Result>("Usp_GetFunctionsForUser " + userid);
            CacheMgr.SetData(cacheKey, prmisslist);
            data = prmisslist;
        }

        return data as List<Usp_GetFunctionsForUser_Result>;
    }

        #endregion
    }
}
